#!/bin/bash
### BEGIN INIT INFO
# Provides: startserver
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start nodejs server
### END INIT INFO

DAEMON="/home/updateProject.sh" #ligne de commande du programme, attention à l'extension .py.
DAEMONUSER="root" #utilisateur du programme
daemon_NAME="startserver" #Nom du programme (doit être identique à l'exécutable).

d_start () {
    /home/updateProject.sh
}
 
#d_stop () {
#}
 
d_restart () {
    d_start
}
 
d_list () {
    /home/updateProject.sh
}
 
case "$1" in
    start|stop|list)
        d_${1}
        ;;
 
    restart|reload)
        d_restart
        ;;

    *)
        echo "Usage: /etc/init.d/$daemon_NAME {start|restart|reload}"
        exit 1
        ;;
esac
exit 0